# This file configures automatic labelling of pr's

'pkg: backend': packages/backend/**/*
'pkg: frontend': packages/frontend/**/*
'pkg: auth': packages/auth/**/*
'pkg: map': packages/mock-account-provider/**/*

# Add 'type: documentation' label to any change to *.md files
'type: ci':
  - .github/*
  - .github/**/*

# Add 'type: documentation' label to any change to *.md files
'type: documentation':
  - .github/*.md
  - '*.md'
  - packages/**/*.md

'type: source':
  - packages/backend/src/**/*
  - packages/frontend/src/**/*
  - packages/auth/src/**/*

# Add 'type: tests' label to any change to *.test.ts files
'type: tests': packages/**/*.test.ts

'type: localenv': infrastructure/local/*
