env:
  browser: true
  es2021: true
  node: true
  jest: true
  amd: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }]
overrides:
  - files: ["*.js"]
    rules:
      "@typescript-eslint/no-var-requires": "off"
