ignore:
  - vulnerability: CVE-2026-23950
  - vulnerability: CVE-2026-23745

  # CVE-2025-64756
  - vulnerability: CVE-2025-64756
  - vulnerability: GHSA-5j98-mcp5-4vw2

  # CVE-2026-24842
  - vulnerability: CVE-2026-24842
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: GHSA-34x7-hfp2-rc4v
