CREATE USER backend WITH PASSWORD 'backend';
CREATE DATABASE backend;
GRANT ALL ON DATABASE backend TO backend;

CREATE USER auth WITH PASSWORD 'auth';
CREATE DATABASE auth;
GRANT ALL ON DATABASE auth TO auth;
