CREATE USER cloud_nine_wallet_test_backend WITH PASSWORD 'cloud_nine_wallet_test_backend';
CREATE DATABASE cloud_nine_wallet_test_backend;
ALTER DATABASE cloud_nine_wallet_test_backend OWNER TO cloud_nine_wallet_test_backend;

CREATE USER cloud_nine_wallet_test_auth WITH PASSWORD 'cloud_nine_wallet_test_auth';
CREATE DATABASE cloud_nine_wallet_test_auth;
ALTER DATABASE cloud_nine_wallet_test_auth OWNER TO cloud_nine_wallet_test_auth;

CREATE USER happy_life_bank_test_backend WITH PASSWORD 'happy_life_bank_test_backend';
CREATE DATABASE happy_life_bank_test_backend;
ALTER DATABASE happy_life_bank_test_backend OWNER TO happy_life_bank_test_backend;

CREATE USER happy_life_bank_test_auth WITH PASSWORD 'happy_life_bank_test_auth';
CREATE DATABASE happy_life_bank_test_auth;
ALTER DATABASE happy_life_bank_test_auth OWNER TO happy_life_bank_test_auth;