name: "Version hierarchy image pusher"
description: "Will re-tag the docker image to create images for parent versions. For example, if the image is tagged 1.2.3, it will create a tag for 1.2 and 1.0 as well."

inputs:
  app_name:
    description: "The name of the application."
    required: true
  package:
    required: true
    description: "Package we are building, for example, 'rafiki-auth' or 'rafiki-backend'."
  platform_name:
    required: true
    description: "Platform we are building for, for example, 'amd64' or 'arm64'."
  gh_token:
    description: "GitHub token to use for authentication."
    required: true
  version:
    required: true
    description: "Version we are tagging as, for example v1.2.3 or v1.2.3-rc1"
  
  
runs:
  using: "composite"
  steps:
    - name: Calculate version hierarchy
      id: hierarchy
      uses: ./.github/actions/parent-versions
      with:
        version: ${{ inputs.version }}
    - name: Fetch docker image from cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/${{ github.sha }}-${{ inputs.package }}-${{ inputs.platform_name }}-${{ inputs.version }}.tar
        key: ${{ github.sha }}-${{ inputs.package }}-${{ inputs.platform_name }}-${{ inputs.version }}
        fail-on-cache-miss: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.gh_token }}
    - name: Load image into Docker
      shell: bash
      run: |
        docker load --input /tmp/${{ github.sha }}-${{ inputs.package }}-${{ inputs.platform_name }}-${{ inputs.version }}.tar
    - name: List docker images
      shell: bash
      run: docker images
    - name: Push to registry
      shell: bash
      run: |
        echo "Pushing image to registry"
        docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.version }}
    - name: Tag and push parent versions
      shell: bash
      if: ${{ steps.hierarchy.outputs.has_hierarchy == 'true' }}
      run: |
        echo "Tagging parent versions with ${{ inputs.version }}, ${{ steps.hierarchy.outputs.minor_parent }} and ${{ steps.hierarchy.outputs.major_parent }}"
        docker tag ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.version }} ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name}}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ steps.hierarchy.outputs.major_parent }}
        docker tag ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.version }} ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name}}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ steps.hierarchy.outputs.minor_parent }}

        echo "Pushing parent tagged images to registry"
        docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ steps.hierarchy.outputs.major_parent }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}-${{ inputs.package }}-${{ inputs.platform_name }}:${{ steps.hierarchy.outputs.minor_parent }}
