### 1. HSM-ILF: Generate ZMK
POST http://localhost:5002/hsm-ilf/generate-zmk
Content-Type: application/json

{}


> {%
  client.global.set("zmk_component1", response.body.component1);
  client.global.set("zmk_component2", response.body.component2);
  client.global.set("zmk_component3", response.body.component3);
  client.global.set("zmk_kcv", response.body.kcv);
  client.global.set("zmk_tr31_lmk_ilf", response.body.tr31Block);
%}


### 2. Import the ZMK @ KaiOS:
POST http://localhost:5002/hsm-kai/import-zmk
content-type: application/json

{
  "component1": "{{zmk_component1}}",
  "component2": "{{zmk_component2}}",
  "component3": "{{zmk_component3}}",
  "kcv": "{{zmk_kcv}}"
}


> {%
  client.global.set("zmk_tr31_lmk_kai", response.body.tr31Block);
%}


### 3. Import the ZMK @ Austria Card:
POST http://localhost:5002/hsm-austria-card/import-zmk
content-type: application/json

{
  "component1": "{{zmk_component1}}",
  "component2": "{{zmk_component2}}",
  "component3": "{{zmk_component3}}",
  "kcv": "{{zmk_kcv}}"
}


> {%
  client.global.set("zmk_tr31_lmk_austria_card", response.body.tr31Block);
%}


### 4. Generate a TMK @ KaiOS, export under ZMK:
POST http://localhost:5002/hsm-kai/generate-tmk
content-type: application/json

{
  "terminalSerial": "KAISN0000111",
  "zmkUnderLmk": "{{zmk_tr31_lmk_kai}}"
}


> {%
  client.global.set("tmk_tr31_lmk_kai", response.body.tr31TmkUnderLmk);
  client.global.set("tmk_tr31_zmk", response.body.tr31TmkUnderZmk);
  client.global.set("tmk_serial", response.body.terminalSerial);
  client.global.set("tmk_kcv", response.body.kcv);
%}


### 5. Import the generated TMK @ ILF under ZMK:
### At this point, the terminal has the TMK, so we can transport keys to the device/terminal securely (once TMK imported).
POST http://localhost:5002/hsm-ilf/import-tmk
content-type: application/json

{
  "tr31TmkUnderZmk": "{{tmk_tr31_zmk}}",
  "tr31ZmkUnderLmk": "{{zmk_tr31_lmk_ilf}}",
  "kcv": "{{tmk_kcv}}"
}


> {%
  client.global.set("tmk_tr31_lmk_ilf", response.body.tr31TmkUnderLmk);
%}


### 6. Generate a Card KeyPair @ ILF, export under ZMK:
POST http://localhost:5002/hsm-ilf/generate-card-key
content-type: application/json

{
  "tr31ZmkUnderLmk": "{{zmk_tr31_lmk_ilf}}"
}


> {%
  client.global.set("cardkey_tr31_lmk_ilf", response.body.tr31CardKeyUnderLmk);
  client.global.set("cardkey_tr31_zmk", response.body.tr31CardKeyUnderZmk);
  client.global.set("cardkey_public", response.body.publicKey);
  client.global.set("cardkey_kcv", response.body.kcv);
%}


### 7. import Card PrivateKey @ AustriaCard:
POST http://localhost:5002/hsm-austria-card/import-card-key
content-type: application/json

{
  "tr31ZmkUnderLmk": "{{zmk_tr31_lmk_austria_card}}",
  "tr31CardKeyUnderZmk": "{{cardkey_tr31_zmk}}",
  "kcv": "{{cardkey_kcv}}"
}


> {%
  client.global.set("cardkey_tr31_lmk_austria_card", response.body.tr31CardKeyUnderLmk);
%}
