{
 "title": "Example Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Transaction Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(increase(packet_amount_fulfill_total[30s]) * 0.5 * 0.0001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces > 100ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "9bab4a0a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "RAFIKI_NETWORK" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "100ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (source) (round(increase(transactions_total[30s]) * 0.5))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ILP Pay Time Quartile Approximations",
   "type": "stat",
   "description": "Maximum time it takes to complete the fastest 25%/50%/75% of ILP payments.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, ilp_pay_time_ms_bucket)",
     "legendFormat": "First Quartile"
    },
    {
     "expr": "histogram_quantile(0.50, ilp_pay_time_ms_bucket)",
     "legendFormat": "Second Quartile"
    },
    {
     "expr": "histogram_quantile(0.75, ilp_pay_time_ms_bucket)",
     "legendFormat": "Third Quartile"
    }
   ]
  },
  {
   "title": "ILP Quote Time Quartile Approximations",
   "type": "stat",
   "description": "Maximum time it takes to complete the fastest 25%/50%/75% of ILP quotes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, ilp_rate_probe_time_ms_bucket)",
     "legendFormat": "First Quartile"
    },
    {
     "expr": "histogram_quantile(0.50, ilp_rate_probe_time_ms_bucket)",
     "legendFormat": "Second Quartile"
    },
    {
     "expr": "histogram_quantile(0.75, ilp_rate_probe_time_ms_bucket)",
     "legendFormat": "Third Quartile"
    }
   ]
  }
 ]
}