{
 "title": "Jason - Example Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "PrometheusDS", "query": "prometheus" },
   { "name": "TempoDS", "query": "tempo" }
  ]
 },
 "panels": [
  {
   "title": "Quote Service Create Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(quote_service_create_time_ms_sum[$__rate_interval])/rate(quote_service_create_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(quote_service_create_resolve_receiver_time_ms_sum[$__rate_interval])/rate(quote_service_create_resolve_receiver_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(quote_service_create_get_quote_time_ms_sum[$__rate_interval])/rate(quote_service_create_get_quote_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(quote_service_create_get_latest_fee_time_ms_sum[$__rate_interval])/rate(quote_service_create_get_latest_fee_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(quote_service_create_insert_time_ms_sum[$__rate_interval])/rate(quote_service_create_insert_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(quote_service_finalize_quote_ms_sum[$__rate_interval])/rate(quote_service_finalize_quote_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "ILP Payment Service getQuote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(quote_service_create_get_quote_time_ms_sum[$__rate_interval])/rate(quote_service_create_get_quote_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(ilp_rate_probe_time_ms_sum[$__rate_interval])/rate(ilp_rate_probe_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(ilp_get_quote_rate_time_ms_sum[$__rate_interval])/rate(ilp_get_quote_rate_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(ilp_make_ilp_plugin_connect_time_ms_sum[$__rate_interval])/rate(ilp_make_ilp_plugin_connect_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(ilp_plugin_close_connect_time_ms_sum[$__rate_interval])/rate(ilp_plugin_close_connect_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(ilp_plugin_disconnect_time_ms_sum[$__rate_interval])/rate(ilp_plugin_disconnect_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Outgoing Payment Service Create Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(outgoing_payment_service_create_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_create_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_create_quote_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_create_quote_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_getwalletaddress_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_getwalletaddress_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_insertgrant_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_insertgrant_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_insertpayment_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_insertpayment_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_getreceiver_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_getreceiver_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_getpeer_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_getpeer_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_patchpeer_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_patchpeer_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "rate(outgoing_payment_service_webhook_event_time_ms_sum[$__rate_interval])/rate(outgoing_payment_service_webhook_event_time_ms_count[$__rate_interval])",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Quote Service Create Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(quote_service_create_time_ms_sum[$__rate_interval])/rate(quote_service_create_time_ms_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(increase(packet_amount_fulfill_total[30s]) * 0.5 * 0.0001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces > 100ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "9bab4a0a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "RAFIKI_NETWORK" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "100ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (source) (round(increase(transactions_total[30s]) * 0.5))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graphql Resolver Duration (95th Percentile)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"^(mutation|query).*\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ILP Pay Time Quartile Approximations",
   "type": "stat",
   "description": "Maximum time it takes to complete the fastest 25%/50%/75% of ILP payments.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, ilp_pay_time_ms_bucket)",
     "legendFormat": "First Quartile"
    },
    {
     "expr": "histogram_quantile(0.50, ilp_pay_time_ms_bucket)",
     "legendFormat": "Second Quartile"
    },
    {
     "expr": "histogram_quantile(0.75, ilp_pay_time_ms_bucket)",
     "legendFormat": "Third Quartile"
    }
   ]
  },
  {
   "title": "ILP Quote Time Quartile Approximations",
   "type": "stat",
   "description": "Maximum time it takes to complete the fastest 25%/50%/75% of ILP quotes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, ilp_rate_probe_time_ms_bucket)",
     "legendFormat": "First Quartile"
    },
    {
     "expr": "histogram_quantile(0.50, ilp_rate_probe_time_ms_bucket)",
     "legendFormat": "Second Quartile"
    },
    {
     "expr": "histogram_quantile(0.75, ilp_rate_probe_time_ms_bucket)",
     "legendFormat": "Third Quartile"
    }
   ]
  }
 ]
}