{
 "title": "TESTNET Network Insights Local",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "asset_code",
    "label": "asset_code",
    "query": {
     "query": "label_values(transactions_amount_total, asset_code)"
    }
   },
   { "name": "PrometheusDS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Transaction Count (by source)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (source) (increase(transactions_total[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (sum by(source) (increase(transactions_total[$__interval])))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Value Sent Through Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(transactions_amount_total[$__interval])* 0.0001 ) ",
     "legendFormat": "Total "
    }
   ]
  },
  {
   "title": "Transaction Average Amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(transactions_amount_total[$__interval])) / sum (increase(transactions_total[$__interval])) * 0.0001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count (by source)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (source) (increase(transactions_total[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (sum by(source) (increase(transactions_total[$__interval])))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Value Sent Through Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(transactions_amount_total[$__interval])* 0.0001 ) ",
     "legendFormat": "Total "
    }
   ]
  },
  {
   "title": "Transaction Average Amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(transactions_amount_total[$__interval])) / sum (increase(transactions_total[$__interval])) * 0.0001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count (by source)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (source) (increase(transactions_total[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (sum by(source) (increase(transactions_total[$__interval])))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Value Sent Through Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(transactions_amount_total[$__interval])* 0.0001 ) ",
     "legendFormat": "Total "
    }
   ]
  },
  {
   "title": "Transaction Average Amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(transactions_amount_total[$__interval])) / sum (increase(transactions_total[$__interval])) * 0.0001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count (by source)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (source) (increase(transactions_total[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (sum by(source) (increase(transactions_total[$__interval])))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Value Sent Through Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (increase(transactions_amount_total[$__interval])* 0.0001 ) ",
     "legendFormat": "Total "
    }
   ]
  },
  {
   "title": "Transaction Average Amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(transactions_amount_total[$__interval])) / sum (increase(transactions_total[$__interval])) * 0.0001",
     "legendFormat": "Transaction average amount"
    }
   ]
  },
  {
   "title": "Transaction Time Distribution",
   "type": "bargauge",
   "description": "Distribution of the time in milliseconds it takes to complete an ILP payment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ilp_pay_time_ms_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Transaction Time",
   "type": "stat",
   "description": "The average time in milliseconds to complete an ILP payment",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilp_pay_time_ms_sum/ilp_pay_time_ms_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shorter Than 500m",
   "type": "stat",
   "description": "Percent of ILP payments that completed in less than or equal to 50ms",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilp_pay_time_ms_bucket{le=\"50\"} / ignoring (le) ilp_pay_time_ms_count ## not sure if 50 is best. should be whatever our target is. if we dont have one then can probably delete this visualization",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quartile Approximations",
   "type": "stat",
   "description": "Maximum time it takes to complete the fastest 25%/50%/75% of ILP payments.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, ilp_pay_time_ms_bucket)",
     "legendFormat": "First Quartile"
    },
    {
     "expr": "histogram_quantile(0.50, ilp_pay_time_ms_bucket)",
     "legendFormat": "Second Quartile"
    },
    {
     "expr": "histogram_quantile(0.75, ilp_pay_time_ms_bucket)",
     "legendFormat": "Third Quartile"
    }
   ]
  },
  {
   "title": "Transaction Time Distribution Over Time",
   "type": "heatmap",
   "description": "Distribution over time of the time in milliseconds it takes to complete an ILP payment.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(ilp_pay_time_ms_bucket[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(transactions_total[5m]))",
     "legendFormat": "Number of transactions completed"
    }
   ]
  }
 ]
}