/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const docs = [
  {
    label: 'Introduction',
    type: 'category',
    items: ['introduction/overview', 'introduction/architecture']
  },
  {
    label: 'Concepts',
    type: 'category',
    items: [
      {
        type: 'category',
        label: 'Interledger Protocol',
        items: [
          'concepts/interledger-protocol/overview',
          'concepts/interledger-protocol/connector',
          'concepts/interledger-protocol/peering'
        ]
      },
      {
        type: 'category',
        label: 'Open Payments',
        items: [
          'concepts/open-payments/overview',
          'concepts/open-payments/key-registry',
          'concepts/open-payments/grant-interaction'
        ]
      },
      {
        type: 'category',
        label: 'Accounting',
        items: [
          'concepts/accounting/assets',
          'concepts/accounting/accounts-and-transfers',
          'concepts/accounting/liquidity',
          'concepts/accounting/tigerbeetle'
        ]
      },
      'concepts/account-servicing-entity',
      'concepts/asset'
    ]
  },
  {
    type: 'category',
    label: 'Integration',
    items: [
      'integration/getting-started',
      'integration/deployment',
      'integration/management',
      'integration/event-handlers'
    ]
  },
  {
    type: 'category',
    label: 'Local Playground',
    items: ['playground/overview']
  },
  {
    type: 'category',
    label: 'Reference',
    items: ['reference/glossary']
  }
]

const apis = {
  'Backend Admin API': [
    {
      type: 'autogenerated',
      dirName: 'apis/backend'
    }
  ],
  'Auth Admin API': [
    {
      type: 'autogenerated',
      dirName: 'apis/auth'
    }
  ]
}

module.exports = {
  docs,
  apis
}
