/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const docs = [
  {
    type: 'doc',
    id: 'introduction',
    label: 'Introduction'
  },
  {
    label: 'Glossary',
    type: 'category',
    items: [
      {
        type: 'autogenerated',
        dirName: 'glossary'
      }
    ]
  }
]

const reference = {
  'API Reference': [{ type: 'autogenerated', dirName: 'reference' }]
}

module.exports = {
  docs,
  reference
}
